# Generated by Django 2.2.13 on 2020-12-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0010_auto_20201127_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitrequest',
            options={'permissions': [('amend_permit_request', 'Traiter les demandes'), ('validate_permit_request', 'Valider les demandes'), ('classify_permit_request', 'Classer les demandes'), ('edit_permit_request', 'Éditer les demandes')], 'verbose_name': '3.1 Consultation de la demande', 'verbose_name_plural': '3.1 Consultation des demandes'},
        ),
        migrations.AlterField(
            model_name='historicalpermitrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Analyse de la fiduciaire'),
        ),
        migrations.AlterField(
            model_name='historicalpermitrequest',
            name='exemption',
            field=models.TextField(blank=True, verbose_name='Analyse du service pilote'),
        ),
        migrations.AlterField(
            model_name='historicalpermitrequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Analyse de la fiduciaire'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='exemption',
            field=models.TextField(blank=True, verbose_name='Analyse du service pilote'),
        ),
        migrations.AlterField(
            model_name='permitrequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Montant'),
        ),
    ]
